### ISSUE TITLE
static-pie currently crashes

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1175]
This is a tracking issue for upstream problems with static-pie.

* Currently lld generates relocatable sections with static-pie that glibc crashes on.
  * This will be fixed with lld 13.0 when it releases near the end of September
* Currently shared_mutexes crash static and static-pie executables
  * This seems to be a quirk with static and weak symbols
  * Happens with both gcc and clang
  * Theoretically will be fixed with glibc 2.34 which releases around August 1st.

**Comment by Sonicadvance1** [comment]
```C++
// clang++ -std=c++20 -g -static -o shared_mutex_crash shared_mutex_crash.cpp -lpthread
#include <shared_mutex>
#include <mutex>
#include <thread>

std::shared_mutex share{};
void EnableThread() {
  // This lock will hit __glibcxx_rwlock_wrlock
  // This then checks the return of __gthread_active_p
  // if true it calls __gthrw__(pthread_rwlock_wrlock)(__rwlock);
  // else just returns 0
  //
  // __gthrw__(pthread_rwlock_wrlock) jumps to zero or ELF base
  // depending on static or static pie
  std::unique_lock lk{share};

}

int main() {
  // Spins up a thread
  // Does this just to change some pthread behaviour around `__gthread_active_p`
  // Now that we have another thread spun up, `__gthread_active_p` should return not zero
  std::thread t(EnableThread);
  t.join();
  printf("Didn't crash?\n");
  return 0;
}
```

Simple example that shows the shared_mutex crashing.

**Comment by Sonicadvance1** [comment]
Additional symbols that could potentially cause us to fault if missing with static-pie.
```
ryanh@Ryan-TR2:/mnt/Work/Work/work/FEXNew/Build$ readelf -W -a ./Bin/FEXLoader | ag "0000000000000000.*0 NOTYPE.*WEAK"
  8210: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
  8211: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
  8212: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
  8213: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_finalize
  9615: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _pthread_cleanup_push_defer
  9616: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _pthread_cleanup_pop_restore
  9619: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __pthread_cleanup_upto
 11413: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_RU1
 11414: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ZGTtnam
 11415: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_memcpyRtWn
 11417: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_RU8
 11420: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_addUserCommitAction
 11424: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_memcpyRnWt
 11431: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ZGTtdlPv
 ```
 To find these you must build with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` since otherwise our release build strips these symbols.

**Comment by Sonicadvance1** [comment]
```
__gmon_start__ - Expected to be zero unless compiled with -pg
_ITM_deregisterTMCloneTable - Transactional memory library. Safe to be zero
_ITM_registerTMCloneTable     - Transactional memory library. Safe to be zero
**__cxa_finalize - call destructors of global (or local static) C++ objects and exit functions registered with atexit**
**_pthread_cleanup_push_defer - Used by pthread_cleanup_push_defer_np**
**_pthread_cleanup_pop_restore - Used by pthread_cleanup_pop_restore_np**
**__pthread_cleanup_upto - Used by _longjmp_unwind, which is used by longjump**
_ITM_RU1- Transactional memory library. Only used when an allocation has an exception in ITM.
_ZGTtnam - Transactional memory library. Transactional new
_ITM_memcpyRtWn - Transactional memory library. Only used when an allocation has an exception in ITM.
_ITM_RU8 - Transactional memory library. Used to read a pointer with shared strings in ITM?
_ITM_addUserCommitAction - Transactional memory library. Used for commiting actions and shared strings?
_ITM_memcpyRnWt  - Transactional memory library. Only used for transactional string constructors?
_ZGTtdlPv - Transactional memory library. Transactional delete
```

I've documented and marked which symbols are likely to cause us problems.

**Comment by Sonicadvance1** [comment]
Using clang+lld13 on AArch64, static-pie crashes inside of `_dl_relocate_static_pie`
Switching over to gnu ld has static-pie working

**Comment by Sonicadvance1** [comment]
Bug tracker for this problem on the llvm side. https://bugs.llvm.org/show_bug.cgi?id=49672
Apparently they are claiming it is a glibc bug.

**Comment by Sonicadvance1** [comment]
condition_variable destructor is broken on AArch64 host. Compile with either clang or GCC it results in a crash.
```
Thread 11 "es2_info:gdrv0" received signal SIGSEGV, Segmentation fault.
0x0000007ff7953dc8 in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
(gdb) bt
#0  0x0000007ff7953dc8 in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#1  0x0000007ff75e48dc in Event::~Event (this=0x7f17c96e90) at ../External/FEXCore/include/FEXCore/Utils/Event.h:29
#2  0x0000007ff75e4fd4 in FEXCore::Core::InternalThreadState::~InternalThreadState (this=0x7f17c96e00) at ../External/FEXCore/include/FEXCore/Debug/InternalThreadState.h:72
#3  0x0000007ff75e7f00 in FEXCore::Context::Context::DestroyThread (this=0x7ff70bd000, Thread=0x7f17c96e00) at ../External/FEXCore/Source/Interface/Core/Core.cpp:550
#4  0x0000007ff75e6bbc in FEXCore::Context::Context::ExecutionThread (this=0x7ff70bd000, Thread=0x7f17c96e00) at ../External/FEXCore/Source/Interface/Core/Core.cpp:1272
#5  0x0000007ff75e6d9c in FEXCore::Context::ThreadHandler (Data=0x7f17b6de10) at ../External/FEXCore/Source/Interface/Core/Core.cpp:443
#6  0x0000007ff7883270 in start_thread (arg=0x0) at pthread_create.c:481
#7  0x0000007ff7a5af5c in thread_start ()
(gdb) frame 1
#1  0x0000007ff75e48dc in Event::~Event (this=0x7f17c96e90) at ../External/FEXCore/include/FEXCore/Utils/Event.h:29
29        }
(gdb) disas
Dump of assembler code for function _ZN5EventD2Ev:
   0x0000007ff75e48c0 <+0>:     sub     sp, sp, #0x20
   0x0000007ff75e48c4 <+4>:     stp     x29, x30, [sp, #16]
   0x0000007ff75e48c8 <+8>:     add     x29, sp, #0x10
   0x0000007ff75e48cc <+12>:    str     x0, [sp, #8]
   0x0000007ff75e48d0 <+16>:    ldr     x8, [sp, #8]
   0x0000007ff75e48d4 <+20>:    add     x0, x8, #0x38
   0x0000007ff75e48d8 <+24>:    bl      0x7ff7953db0 <_ZNSt18condition_variableD2Ev>
=> 0x0000007ff75e48dc <+28>:    ldp     x29, x30, [sp, #16]
   0x0000007ff75e48e0 <+32>:    add     sp, sp, #0x20
   0x0000007ff75e48e4 <+36>:    ret
End of assembler dump.
(gdb) disas _ZNSt18condition_variableD2Ev,+64
Dump of assembler code from 0x7ff7953db0 to 0x7ff7953df0:
   0x0000007ff7953db0 <_ZNSt18condition_variableD2Ev+0>:        nop
   0x0000007ff7953db4:  nop
   0x0000007ff7953db8:  nop
   0x0000007ff7953dbc:  nop
   0x0000007ff7953dc0 <_ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE+0>:    stp     x29, x30, [sp, #-16]!
   0x0000007ff7953dc4 <_ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE+4>:    mov     x29, sp
   0x0000007ff7953dc8 <_ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE+8>:    ldr     x1, [x1]
   ```
   
   Repro case.
   ```C++
   #include <condition_variable>

__attribute__((noinline))
static void DoCV(int a, int b) {
  // This function just sets x1 to zero to see the fastest crash
  std::condition_variable cv{};
}
int main() {
  DoCV(0, 0);
  return 0;
}
```
