### ISSUE TITLE
F1: 2015 launcher thinks it is running on a Mac

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#1429]
When it starts running under FEX the game has a popup saying something along the lines of "This Mac is unsupported"

We should figure out why the game thinks it is running on a Mac

**Comment by Sonicadvance1** [comment]
This has graduated from a FEX not working game to a Linux not working game at all.
This is no longer our problem, it's a dead Linux game.

Backtrace
```
#0  0x0000000000d09227 in  ()
#1  0x00000000005b7a3f in  ()
#2  0x00000000005cf1c9 in  ()
#3  0x00000000005cf58f in  ()
#4  0x00000000005d4d63 in  ()
#5  0x0000000000e8ca52 in  ()
#6  0x0000000000e8caa9 in  ()
#7  0x0000000000d65363 in  ()
#8  0x000000000093f935 in  ()
#9  0x00007ffff2ab5927 in start_thread (arg=<optimized out>) at pthread_create.c:435
#10 0x00007ffff2b459e4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
(gdb)

Dump of assembler code from 0xd09227 to 0xd09247:
=> 0x0000000000d09227:	mov    rdx,QWORD PTR [rdx+0x40]
   0x0000000000d0922b:	jmp    rdx
   0x0000000000d0922d:	nop

rdx            0x7ff9165391b6      140707798159798

rdx pointer is pointing entirely to unmapped memory space.
```
