### ISSUE TITLE
SIGSEGV in Frontend when running wine + Multiblock

### ISSUE THREAD

**Issue by CallumDev** [FEX-Emu/FEX#1517]
Running `wine notepad.exe` on an AArch64 host attempts to load from address `0xffffffffff470dc0` causing a SIGSEGV. Possible unintentional sign extension from `ff470dc0`.

**Comment by CallumDev** [comment]
gdb `disas $pc-128,+256`:

```
   0x0000aaaaba7639fc:	mov	x29, x0
   0x0000aaaaba763a00:	str	x23, [x0, #32]
   0x0000aaaaba763a04:	ldr	x8, [sp, #104]
   0x0000aaaaba763a08:	ldr	x9, [x8, #16]
   0x0000aaaaba763a0c:	cbz	x9, 0xaaaaba763dc8
   0x0000aaaaba763a10:	mov	x21, x9
   0x0000aaaaba763a14:	ldr	x8, [x9, #32]
   0x0000aaaaba763a18:	add	x9, x9, #0x10
   0x0000aaaaba763a1c:	add	x10, x21, #0x18
   0x0000aaaaba763a20:	cmp	x23, x8
   0x0000aaaaba763a24:	csel	x9, x9, x10, cc  // cc = lo, ul, last
   0x0000aaaaba763a28:	ldr	x9, [x9]
   0x0000aaaaba763a2c:	cbnz	x9, 0xaaaaba763a10
   0x0000aaaaba763a30:	cmp	x23, x8
   0x0000aaaaba763a34:	mov	x0, x21
   0x0000aaaaba763a38:	b.cs	0xaaaaba763de0  // b.hs, b.nlast
   0x0000aaaaba763a3c:	ldr	x8, [sp, #104]
   0x0000aaaaba763a40:	ldr	x8, [x8, #24]
   0x0000aaaaba763a44:	cmp	x21, x8
   0x0000aaaaba763a48:	b.ne	0xaaaaba763dd8  // b.any
   0x0000aaaaba763a4c:	b	0xaaaaba763dec
   0x0000aaaaba763a50:	ldr	x9, [x19, #48]
   0x0000aaaaba763a54:	ldr	x10, [x19, #16]
   0x0000aaaaba763a58:	b	0xaaaaba763a7c
   0x0000aaaaba763a5c:	ldr	x12, [x19, #72]
   0x0000aaaaba763a60:	ldr	w13, [x12, #12]
   0x0000aaaaba763a64:	orr	w13, w13, #0x2
   0x0000aaaaba763a68:	str	w13, [x12, #12]
   0x0000aaaaba763a6c:	and	w11, w11, #0xff
   0x0000aaaaba763a70:	add	x8, x8, #0x1
   0x0000aaaaba763a74:	cmp	w11, #0xf
   0x0000aaaaba763a78:	b.eq	0xaaaaba763808  // b.none
=> 0x0000aaaaba763a7c:	ldrb	w2, [x9, x8]
   0x0000aaaaba763a80:	add	x11, x19, x8
   0x0000aaaaba763a84:	strb	w2, [x11, #57]
   0x0000aaaaba763a88:	add	w11, w8, #0x1
   0x0000aaaaba763a8c:	strb	w11, [x19, #56]
   0x0000aaaaba763a90:	cmp	w2, #0xef
   0x0000aaaaba763a94:	b.gt	0xaaaaba763acc
   0x0000aaaaba763a98:	sub	w12, w2, #0xf
   0x0000aaaaba763a9c:	cmp	w12, #0x58
   0x0000aaaaba763aa0:	b.hi	0xaaaaba763bc4  // b.pmore
   0x0000aaaaba763aa4:	adr	x13, 0xaaaaba763a5c
   0x0000aaaaba763aa8:	ldrb	w14, [x27, x12]
   0x0000aaaaba763aac:	add	x13, x13, x14, lsl #2
   0x0000aaaaba763ab0:	br	x13
   0x0000aaaaba763ab4:	ldrb	w12, [x10, #124]
   0x0000aaaaba763ab8:	cbnz	w12, 0xaaaaba763a6c
   0x0000aaaaba763abc:	ldr	x12, [x19, #72]
   0x0000aaaaba763ac0:	ldr	w13, [x12, #12]
   0x0000aaaaba763ac4:	orr	w13, w13, #0x800
   0x0000aaaaba763ac8:	b	0xaaaaba763a68
   0x0000aaaaba763acc:	cmp	w2, #0xf0
   0x0000aaaaba763ad0:	b.eq	0xaaaaba763b98  // b.none
   0x0000aaaaba763ad4:	cmp	w2, #0xf2
   0x0000aaaaba763ad8:	b.eq	0xaaaaba763ba8  // b.none
   0x0000aaaaba763adc:	cmp	w2, #0xf3
   0x0000aaaaba763ae0:	b.ne	0xaaaaba763bc4  // b.any
   0x0000aaaaba763ae4:	ldr	x12, [x19, #72]
   0x0000aaaaba763ae8:	ldr	w13, [x12, #12]
   0x0000aaaaba763aec:	orr	w13, w13, #0x20000
   0x0000aaaaba763af0:	str	w13, [x12, #12]
   0x0000aaaaba763af4:	mov	w13, #0xf3                  	// #243
   0x0000aaaaba763af8:	strb	w13, [x12, #19]


registers: x8 = 0x0, x9 = 0xffffffffff470dc0
mapped (/proc/<tid>/maps): 0xff309000 - 0xff489000
```

**Comment by Sonicadvance1** [comment]
Trying to reproduce this. Which wine is used?
The one in the rootfs or some staging/devel thing?

**Comment by CallumDev** [comment]
rootfs

**Comment by Sonicadvance1** [comment]
Looking at this more closely, this doesn't look to be a crash in JIT code. 
We only generate the `adr` instruction with the AESKeyGenAssist instruction.
Building FEX with debug build and assertions enabled should help. `cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASSERTIONS=True` Hopefully a visible backtrace in gdb.

**Comment by CallumDev** [comment]
The SIGSEGV is actually occurring in the frontend.

```
0x0000aaaaea8507c4 in FEXCore::Frontend::Decoder::ReadByte (this=0xffff9425e000) at ../External/FEXCore/Source/Interface/Core/Frontend.cpp:194
194	  uint8_t Byte = InstStream[InstructionSize];
(gdb) bt
#0  0x0000aaaaea8507c4 in FEXCore::Frontend::Decoder::ReadByte (
    this=0xffff9425e000)
    at ../External/FEXCore/Source/Interface/Core/Frontend.cpp:194
#1  0x0000aaaaea852f8c in FEXCore::Frontend::Decoder::DecodeInstruction (
    this=0xffff9425e000, PC=18446744073697430976)
    at ../External/FEXCore/Source/Interface/Core/Frontend.cpp:855
#2  0x0000aaaaea853d94 in FEXCore::Frontend::Decoder::DecodeInstructionsAtEntry
    (this=0xffff9425e000, 
    _InstStream=0xffffffffff470dc0 <error: Cannot access memory at address 0xffffffffff470dc0>, PC=18446744073697430976)
    at ../External/FEXCore/Source/Interface/Core/Frontend.cpp:1182
#3  0x0000aaaaea81ce0c in FEXCore::Context::Context::GenerateIR (
    this=0xffff94288000, Thread=0xffff9422aa00, GuestRIP=18446744073697430976)
    at ../External/FEXCore/Source/Interface/Core/Core.cpp:684
#4  0x0000aaaaea81eefc in FEXCore::Context::Context::CompileCode (
    this=0xffff94288000, Thread=0xffff9422aa00, GuestRIP=18446744073697430976)
    at ../External/FEXCore/Source/Interface/Core/Core.cpp:863
#5  0x0000aaaaea81f420 in FEXCore::Context::Context::CompileBlock (
    this=0xffff94288000, Frame=0xffff9422ab80, GuestRIP=18446744073697430976)
    at ../External/FEXCore/Source/Interface/Core/Core.cpp:951
#6  0x0000aaaaea81f250 in FEXCore::Context::Context::CompileBlockJit (
    this=0xffff94288000, Frame=0xffff9422ab80, GuestRIP=18446744073697430976)
    at ../External/FEXCore/Source/Interface/Core/Core.cpp:899
#7  0x00000000ff7fe298 in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further
```

**Comment by CallumDev** [comment]
This only occurs when Multiblock is enabled
