### ISSUE TITLE
Test harness doesn't work on recent glibc due to catchsegv removal`

### ISSUE THREAD

**Issue by alyssarosenzweig** [FEX-Emu/FEX#2724]
Trying to run tests on Debian testing

```
alyssa@applejack:~/FEX/Build$ ctest -R 'jit_1/Test_VEX/shlx.asm' --output-on-failure
Test project /home/alyssa/FEX/Build
    Start 5899: jit_1/Test_VEX/shlx.asm
1/1 Test #5899: jit_1/Test_VEX/shlx.asm ..........***Failed    0.03 sec
Traceback (most recent call last):
  File "/home/alyssa/FEX/Scripts/testharness_runner.py", line 58, in <module>
    Process = subprocess.Popen(RunnerArgs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'catchsegv'
```

See also https://gitlab.gnome.org/GNOME/mutter/-/issues/2120

**Comment by Sonicadvance1** [comment]
We should probably just add a cmake check to this to disable catchsegv if not found. It tends to provide zero value even in the CI runners.
