### ISSUE TITLE
Regression from 2408 to 2409 (segfault on running anything)

### ISSUE THREAD

**Issue by theofficialgman** [FEX-Emu/FEX#4148]
Device:

```
OS: Ubuntu noble 24.04 aarch64
Host: Nintendo Switch (2017)
Kernel: Linux 4.9.140-l4t
Uptime: 1 hour, 18 mins
Packages: 3276 (dpkg), 6 (flatpak)
Shell: bash 5.2.21
DE: KDE Plasma 5.27.11
WM: KWin (X11)
WM Theme: Breeze
Theme: Breeze (Light) [Qt], Breeze [GTK2/3/4]
Icons: Breeze [Qt], breeze-dark [GTK2/3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
Cursor: Breeze (24px)
Terminal: /dev/pts/3
CPU: icosa (4) @ 2.09 GHz
GPU: NVIDIA Tegra X1 (nvgpu) [Integrated]
Memory: 1.70 GiB / 3.90 GiB (44%)
Swap: 0 B / 3.00 GiB (0%)
Disk (/): 59.42 GiB / 122.94 GiB (48%) - ext4
Battery: 100% [AC Connected]
Locale: C.UTF-8
```

Starting with 2409 (build from source or the Ubuntu PPA) I get the following error on running any command (such as FEXBash)

```
Illegal instruction (core dumped)
```

This is not an issue on 2408 or previous versions in my testing.

Happy to bisect further if any developer has insight in which change likely could be the cause of this issue

my build (release) only gives the following in gdb bt

```
#0  0x000000555576c904 in FEX::FetchHostFeatures() ()
#1  0x0000005555630dec in main ()
```

so maybe it has something to do with https://github.com/FEX-Emu/FEX/commit/941b065da60494b324aa4efc0d35ab007aa272a4 which was introduced in 2409?

CC: @Azkali @bylaws

**Comment by Sonicadvance1** [comment]
This is due to your kernel being too old to handle ARM's "cpuid" emulation. This change happened with https://github.com/FEX-Emu/FEX/pull/3962
Theoretically our minimum spec of Linux 5.0 should support all the feature registers we query.

**Comment by theofficialgman** [comment]
Gotcha, so the changes that were added in kernel 4.11 for arm64 HWCAP_CPUID are now required (as documented here https://github.com/torvalds/linux/commit/4aa8a472c33f4024381ade56bef008a9c566366a and added here https://github.com/torvalds/linux/commit/77c97b4ee21290f5f083173d957843b615abbff2). Probably more after that but that is the gist of it.

**Comment by AndreRH** [comment]
> This is due to your kernel being too old to handle ARM's "cpuid" emulation. This change happened with https://github.com/FEX-Emu/FEX/pull/3962
> Theoretically our minimum spec of Linux 5.0 should support all the feature registers we query.

What about catching the exception and then expecting no features to be present? Things would run slower, but better than not at all

**Comment by Sonicadvance1** [comment]
Nothing to do on FEX's side here. Our minimum kernel version spec is now 5.15. Even if we worked around the cpuid limitation it would break with our unconditional usage of readat2 and other things.
