### ISSUE TITLE
Parent thread not exiting

### ISSUE THREAD

**Issue by phire** [FEX-Emu/FEX#846]
Reproduction:

``` bash
count=0; while :
do
let "count+=1"; Bin/FEXLoader -T 4 -s --aotir-load -- ../../Geekbench-4.4.4-Linux/geekbench_x86_64 --section 2 --workload 213 && echo worked $count
sleep 1
done
```

Seems to crash sometimes after 10+ iterations on my machine. If you attach with GDB, there is only one thread with the following backtrace:
```
(gdb) bt
#0  0x00007fe468cec9ba in __futex_abstimed_wait_common64 () from /usr/lib/libpthread.so.0
#1  0x00007fe468ce6260 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#2  0x00007fe468bb5bb1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:865
#3  std::condition_variable::wait (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#4  0x00005635538ea6eb in FEXCore::Context::Context::RunUntilExit() ()
#5  0x00005635538ddc9c in main ()
```

**Comment by skmp** [comment]
With #865 I've let this loop over 100 times w/o a lock. Will let it run all day, and will re-open if it locks.
